Document: orphilia-dropbox
Title: Debian orphilia-dropbox Manual
Author: <insert document author here>
Abstract: This manual describes what orphilia-dropbox is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/orphilia-dropbox/orphilia-dropbox.sgml.gz

Format: postscript
Files: /usr/share/doc/orphilia-dropbox/orphilia-dropbox.ps.gz

Format: text
Files: /usr/share/doc/orphilia-dropbox/orphilia-dropbox.text.gz

Format: HTML
Index: /usr/share/doc/orphilia-dropbox/html/index.html
Files: /usr/share/doc/orphilia-dropbox/html/*.html
